version: '3'
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./src:/go/src
    restart: always
    tty: true
